name: '🚀 Circle List Auto Deploy'

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:
  #   inputs:
  #     deployment_target:
  #       description: 'Deployment target'
  #       required: true
  #       default: 'staging'
  #       type: choice
  #       options:
  #         - staging
  #         - production

jobs:
  build-and-deploy:
    environment: ${{ (github.ref == 'refs/heads/master' && 'production') || (github.ref == 'refs/heads/develop' && 'staging') || '' }}
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_JSON }}
      FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: yarn
      
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Install monorepo packages
        run: yarn install

      - name: Deploy to firebase
        env:
          NODE_OPTIONS: "--max_old_space_size=5000"
        run: |
          firebase use ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          firebase target:apply hosting circlelist ${{ (github.ref == 'refs/heads/master' && 'sb-circlelist-prod') || (github.ref == 'refs/heads/develop' && 'sb-circlelist-staging') || '' }}
          firebase deploy --only hosting:circlelist
