name: "🚀 Deploy"

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deployment target'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    environment: ${{ inputs.deployment_target }}
    runs-on: ubuntu-latest

    env:
      VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DATABASE_URL: ${{ vars.VITE_FIREBASE_DATABASE_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}
      VITE_RECAPTCHA_ENTERPRISE_SITEKEY: ${{ vars.VITE_RECAPTCHA_ENTERPRISE_SITEKEY }}
      VITE_SOCKBASE_MANAGE_ORGANIZATION_ID: ${{ vars.VITE_SOCKBASE_MANAGE_ORGANIZATION_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
      
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      
      - name: Install monorepo packages
        run: yarn install
      
      - name: Create .env file
        run: |
          touch ./packages/functions/.env
          echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> ./packages/functions/.env

      - name: Deploy to firebase
        run: |
          firebase use ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          firebase deploy
