name: "💅 Lint functions"
on:
  push:
    path:
      - "packages/functions/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/functions

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      
      - run: |
          corepack enable yarn
          yarn set version 1.22.1
          
      - name: Install monorepo packages
        working-directory: ./
        run: yarn install

      - name: Install packages for functions
        run: yarn install

      - name: Lint functions
        run: yarn lint
