name: "💅 Lint functions"
on:
  push:
    path:
      - "packages/functions/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/functions

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: '8.6.2'
      
      - name: Install monorepo packages
        working-directory: ./
        run: pnpm install

      - name: Install packages for functions
        run: pnpm install

      - name: Lint functions
        run: pnpm lint
